version: '3.9'


services:
  web:
    container_name: app-dev
    restart: unless-stopped
    build:
      context: ./src
      args:
        REQUIREMENTS_FILE: dev-requirements.txt
    ports:
        - "8000:8000"
    env_file:
      - ./src/.env
